name = "GosolCraft"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "findex.toml"
hash-format = "sha256"
hash = "818eed41314ed867c6e5095ae1fbc35839e95989846da04baa70dbcb9dbf1b38"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
