name = "GosolCraft"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb57e560c7f93805d75fe0bd2f21ab5341f631a6a67480e7c97336a816ee09a5"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"
