name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06be7f413090cfa54cfa60117dbc0b6d7bc16f12c0e4e8cb6b6cfdbf93a1f55f"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
