name = "GósolCraft"
author = "guineu"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e1266a4c759cd541d1f89e2893b9e161736b95ad5b11ebb4d4a286c2578c1cd"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
