name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd42d932286da351b734658e9ce7926ce4bdb2d7cd81f8a1a72b2eceafc8b606"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
