name = "Server"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03eee385dc079e29e66a2f5ba5c4e00d0ed6cae378b869f4404a61fdc9609534"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
