name = "Server"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9d415ab3059a6358cc3bd62024bcc5f173ffef980ab993a4c85975954cee736"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
