name = "[IRIS] Complementary 4.4"
filename = "ComplementaryShaders_v4.5.zip"
side = "client"

[option]
optional = true
default = true
description = "Descargar el pack de shaders Complementary 4.4"

[download]
url = "https://media.forgecdn.net/files/3826/772/ComplementaryShaders_v4.5.zip"

hash-format = "sha256"
hash = "55de6d68796f5db8752593b645f25f631ab7eadd8dcf460677b5c619dea4474d"
