name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "600f5428078da4bffc7ddeee1e88a891b4cdb4380a012490e2f327364da33e00"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
