name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "927e603dad40f6220d6450df2879587f1a726cae84dab0c6d8ecfb1e93f76905"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
