name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b1d0fa5b3978b21d73950450efdba28e44e009f334065335909297f0f7ca764"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
