name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e503683ebd273a7a96db92fd517945bb69961c39e3b9ba1c335dbffefe34e6c8"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
