name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6db7284e94a08fab4d71d9516a9c7d225f7a6756c56a2ddf9c7f0d265cd9b350"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
