name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91a180f44be4155fa28c6ac880a17648cf60c3f71373783cddf2c5e2367b70dd"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
