name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e28d0bc79ef67598ee418b848d545770c96e0cabc9c4ac84acc185186b27ed7"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
