name = "Gosol"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08e4c47c265a2c9d6bbf1c3f3e0f3d07cc0c03f53bdb51b160e0f957236f7d30"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
