name = "Gosol Neu"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b5c735df6ff4caf68250767fc7b2380fc29cd1acbbc37503a9ed835c8543c38"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
