name = "Gosol Neu"
author = "guineu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a49a08b09bebc3436b7e6dc00fa87030a37f1e6c75028308ff9d2667a1d487"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.2"
